apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\WINDOWS\system32\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.network/xs2a-net: "true"
    io.kompose.service: certificate-generator
  name: certificate-generator
spec:
  containers:
    - image: 'adorsys/xs2a-certificate-generator:'
      name: certificate-generator
      ports:
        - containerPort: 8092
      resources: {}
  restartPolicy: OnFailure
status: {}
