server:
  port: 8094

keycloak:
  auth-server-url: http://localhost:8080
  realm: ledgers
  resource: ledgers-client
  public-client: false
  principal-attribute: preferred_username
  credentials:
    secret: a61a81cd-7178-40d8-8386-ed02791e6592 #Here should be personal generated secret for client (swap public to 'private?' generate secret, swap to public again)

db:
  host: localhost
  database: consent
  user: cms
  password: cms
  port: 5432
  url: jdbc:postgresql://${db.host}:${db.port}/${db.database}

cms:
  datasource:
    jdbc-url: ${db.url}?currentSchema=consent
    username: ${db.user}
    password: ${db.password}

spring:
  jpa:
    open-in-view: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 2MB
      max-request-size: 2MB
  jackson:
    serialization:
      write_dates_as_timestamps: false
  devtools:
    remote:
      secret: fractal

ledgers.url: http://localhost:8088

license.url: https://www.gnu.org/licenses/agpl-3.0.html

feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        loggerLevel: full

# Cors configuration
management:
  endpoints:
    web:
      cors:
        allow-credentials: true
        allowed-origin-patterns: "*"
        allowed-headers: "*"
        allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
        max-age: 3600
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  health:
    mail:
      enabled: false

app:
  endpoints:
    admin.self.registration.disabled: false
